resources:
  - name: GetFiles
    type: FileSpec
    configuration:
      sourceArtifactory: MyArtifactory
      aql: "{"repo":"docker-local"}"
    
pipelines:
  - name: PropertyDemo
    steps:
      - name: ArtifactoryFiles
        type: Bash
        configurations:
          inputResources:
            - name: GetFiles
        execution:
          onExecute:
            - ls
     
      
