resources:
  - name: GetFiles
    type: FileSpec
    configuration:
      sourceArtifactory: myArtifactory
      pattern: "docker-local"
    
pipelines:
  - name: PropertyDemo
    steps:
      - name: ArtifactoryFiles
        type: Bash
        configuration:
          inputResources:
            - name: GetFiles
        execution:
          onExecute:
            - ls
     
      
